import { Scene } from './types';

// Importing static assets generated by the asset generator
import activitiesImage from './assets/images/activities_illustration_1781067156251.png';
import handshakeImage from './assets/images/union_handshake_illustration_1781067174136.png';
import benefitsImage from './assets/images/benefits_illustration_1781067189636.png';

export const IMAGE_MAP = {
  activities: activitiesImage,
  handshake: handshakeImage,
  benefits: benefitsImage,
  financial: benefitsImage, // Reusing benefits image or we can draw custom charts
  qa: handshakeImage,
  closing: activitiesImage
};

export const INITIAL_SCENES: Scene[] = [
  {
    id: 1,
    title: "Chăm Lo & Gắn Kết Toàn Diện",
    bullets: [
      "Company Trip thú vị hàng năm",
      "Chúc mừng Sinh nhật ấm áp",
      "Giờ vàng Happy Hour vui vẻ",
      "Thưởng & Khen thưởng xứng đáng",
      "Thể thao – Văn nghệ sôi nổi",
      "Hỗ trợ khó khăn kịp thời"
    ],
    voiceOver: "Trong nhiều năm qua, Công ty luôn đồng hành cùng người lao động thông qua nhiều chương trình phúc lợi và hoạt động gắn kết ý nghĩa.",
    start: 0,
    end: 8,
    illustrationType: 'activities',
    textLayout: 'left'
  },
  {
    id: 2,
    title: "Chính Thức Thành Lập Công Đoàn Cơ Sở",
    bullets: [
      "Thời mốc lịch thức: Từ 01/07/2026",
      "Chuẩn hóa công tác chăm sóc CBNV",
      "Đại diện tiếng nói người lao động",
      "Bảo vệ quyền lợi hợp pháp, chính đáng",
      "Đúng tinh thần quy định của pháp luật"
    ],
    voiceOver: "Từ ngày 01/07/2026, Công ty chính thức thành lập Công đoàn cơ sở nhằm chuẩn hóa việc chăm lo, đại diện và bảo vệ quyền lợi người lao động theo quy định của pháp luật.",
    start: 8,
    end: 18,
    illustrationType: 'handshake',
    textLayout: 'center'
  },
  {
    id: 3,
    title: "Cam Kết: Không Cắt Giảm Phúc Lợi",
    bullets: [
      "Duy trì 100% các chương trình sẵn có",
      "Chuẩn hóa quy trình thực hiện rõ ràng",
      "Minh bạch trong các nguồn thu - chi",
      "Bền vững và nâng tầm giá trị phúc lợi"
    ],
    voiceOver: "Các chương trình phúc lợi hiện hữu sẽ không bị cắt giảm. Thay vào đó, các hoạt động chăm lo người lao động sẽ được triển khai thông qua Công đoàn cơ sở với sự đồng hành và hỗ trợ từ Công ty.",
    start: 18,
    end: 30,
    illustrationType: 'benefits',
    textLayout: 'left'
  },
  {
    id: 4,
    title: "Quyền Lợi Độc Quyền Của Đoàn Viên",
    bullets: [
      "🎉 Company Trip vui tươi",
      "🎂 Sinh nhật chu đáo",
      "💍 Chế độ Hiếu hỷ, Kết hôn",
      "👶 Quà mừng Sinh con & Thăm ốm đau",
      "🎁 Quà tặng các dịp Lễ Tết lớn",
      "🏆 Khen thưởng thành tích rực rỡ",
      "🎓 Đào tạo & Nâng cao nghiệp vụ",
      "❤️ Quỹ hỗ trợ CBNV hoàn cảnh khó khăn"
    ],
    voiceOver: "Đoàn viên Công đoàn sẽ được tham gia và thụ hưởng các chương trình như Company Trip, sinh nhật, hiếu hỉ, ốm đau, sinh con, lễ Tết, hoạt động thể thao, đào tạo, khen thưởng và nhiều chương trình chăm lo khác.",
    start: 30,
    end: 40,
    illustrationType: 'benefits',
    textLayout: 'split'
  },
  {
    id: 5,
    title: "Đóng Góp Tài Chính & Đồng Hành",
    bullets: [
      "🏢 Doanh nghiệp: Đóng 2% quỹ lương (kinh phí công đoàn)",
      "💰 Doanh nghiệp: Tiếp tục bổ sung ngân sách đảm bảo chất lượng",
      "👤 Người lao động: Đóng 0,5% đoàn phí đóng góp tự nguyện"
    ],
    voiceOver: "Để duy trì các hoạt động này, Công ty đóng kinh phí công đoàn theo quy định là 2% quỹ lương và tiếp tục hỗ trợ thêm ngân sách để bảo đảm chất lượng phúc lợi như hiện nay.",
    start: 40,
    end: 50,
    illustrationType: 'financial',
    textLayout: 'left'
  },
  {
    id: 6,
    title: "Hỏi Đáp Nhanh Về Công Đoàn (Q&A)",
    bullets: [
      "Q: Không tham gia Công đoàn có ảnh hưởng công việc không?\n-> A: Hoàn toàn không. Việc tham gia là tự nguyện 100%.",
      "Q: Tham gia Công đoàn thì được gì?\n-> A: Được thụ hưởng toàn bộ chương trình chăm lo và phúc lợi.",
      "Q: Ban Giám đốc (BOD) Công ty có còn đồng hành?\n-> A: Có. BOD cam kết tiếp tục tài trợ nguồn lực tối đa."
    ],
    voiceOver: "Có những câu hỏi thường gặp như... Không tham gia Công đoàn có bị ảnh hưởng công việc không? Không, việc tham gia hoàn toàn tự nguyện. Tham gia thì được gì? Được hưởng toàn bộ chính sách chăm sóc đoàn viên. Công ty có còn đồng hành? Chắc chắn có, BOD cam kết tiếp tục chung tay hỗ trợ.",
    start: 50,
    end: 58,
    illustrationType: 'qa',
    textLayout: 'split'
  },
  {
    id: 7,
    title: "Công Đoàn Cơ Sở: Đồng Hành Cùng Phát Triển",
    bullets: [
      "📢 Tiếng nói đại diện tin cậy",
      "🤝 Đồng hành sát cánh mọi lúc",
      "❤️ Chăm lo cuộc sống vật chất & tinh thần",
      "📝 Hướng dẫn đăng ký chi tiết sẽ được HR gửi qua email sắp tới!"
    ],
    voiceOver: "Cùng tham gia Công đoàn cơ sở để xây dựng môi trường làm việc gắn kết, phát triển và bền vững.",
    start: 58,
    end: 60,
    illustrationType: 'closing',
    textLayout: 'center'
  }
];

export const AUDIO_CHORD_PRESETS = [
  { name: "C Major (Peaceful)", freq: [261.63, 329.63, 392.00, 523.25] },
  { name: "F Major (Bright/Moving)", freq: [349.23, 440.00, 523.25, 698.46] },
  { name: "G Major (Inspiring)", freq: [392.00, 493.88, 587.33, 783.99] },
  { name: "A Minor (Emotional)", freq: [220.00, 261.63, 329.63, 440.00] }
];
